### ISSUE TITLE
year 53606 is out of range

### ISSUE THREAD

**Issue by ecumene** [jagregory/cognito-local#40]
When running 

`aws cognito-idp create-user-pool-client --user-pool-id local --client-name client --endpoint http://auth.localhost`

with `.cognito/config.json`
```
{}
```

I get this error:
```
year 53606 is out of range
```

My `docker-compose` looks something like this:

```
auth:
  image: jagregory/cognito-local:3.1.2
  container_name: auth
  restart: always
  ports:
    - 9229:9229
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
    - "traefik.http.routers.auth.entrypoints=web"
```

Does this look familiar? Thanks!
